### ISSUE TITLE
Failing pytest with ModuleNotFoundError when using hatch integration with versioningit-onbuild option

### ISSUE THREAD

**Issue by timonviola** [jwodder/versioningit#89]
I am using v3.1.* with Hatch v1.12.0

I have this in pyproject.toml:

```
[tool.hatch.build.hooks.versioningit-onbuild]
source-file = "src/dagcellent/__init__.py"
build-file = "dagcellent/__init__.py"
require-match = true
```

When I run my tests, it fails:
```
ImportError while importing test module '/Users/timon/work/dagcellent/dagcellent/tests/test_dag_config.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_dag_config.py:7: in <module>
    from dagcellent.dynamic_dag import Config, parse_config_file
E   ModuleNotFoundError: No module named 'dagcellent.dynamic_dag'
```

When I remove the on-build part, it works again.

Any ideas if I am misconfiguring something or how to dig deeper in the problem? It seems like that my package is not in the `test` venv.

p.s. I am willing to submit a PR/provide more info.

**Comment by jwodder** [comment]
> It seems like that my package is not in the `test` venv.

Yes, it certainly seems that way.

Can you provide a link to your source code repository, ideally including the `onbuild` configuration?  If you can't share your code for one reason or another, I'd at the very least need to see an MVCE.

**Comment by timonviola** [comment]
I created an MVCE repo: https://github.com/timonviola/hatch-test

**Comment by jwodder** [comment]
I've figured out what's going wrong: the combination of Hatch, editable/development installs, and versioningit's onbuild hook do not play nice together.  Specifically, the onbuild hook runs for Hatch editable installs (which it's not supposed to, [but I don't know how to stop it](https://github.com/pypa/hatch/issues/1626)), and the behavior of the hook triggers [a bug in Hatch's editable install support](https://github.com/pypa/hatch/issues/1627) that results in only your `dagcellent/__init__.py` file being visible on `sys.path`.

Until someone from Hatch gets back to me on the linked issues, your options are:

* Don't use onbuild
* Don't use editable/development installs; ways to accomplish this include:
    * [Set `tool.hatch.envs.static.dev-mode = false`](https://hatch.pypa.io/latest/config/environment/overview/#dev-mode) (but then you might have to recreate your Hatch envs if your code changes; I'm not sure)
    * Use tox, nox, or similar instead of Hatch's envs

**Comment by jwodder** [comment]
OK, I got a response, and I now have a PR (#90) that should fix the problem.  If I test out the PR on your MVCE by changing the `versioningit` build requirement to `"versioningit @ git+https://github.com/jwodder/versioningit@gh-89"`, then `hatch run test:test` works.  Can you confirm it works in your original code?

**Comment by timonviola** [comment]
Thanks for looking into it. I tried to update my projects, but it is still not working. I updated the example repo with the suggested change, but I still get module not found:
https://github.com/timonviola/hatch-test/commit/da95a3d7ea8d965b2a4047643e338cf49e130452

```diff
-    "versioningit == 3.1.*",
+    "versioningit @ git+https://github.com/jwodder/versioningit@gh-89",
```

Did I make the right config changes?

**Comment by jwodder** [comment]
You need to change the `versioningit` dependency in `build-system.requires`, on [this line](https://github.com/timonviola/hatch-test/blob/da95a3d7ea8d965b2a4047643e338cf49e130452/pyproject.toml#L2).  The `versioningit` in `extra-dependencies` is only for being able to run the `versioningit` command via the `version` script; the command doesn't make use of the "onbuild" code, so it has no relation to the original error.

**Comment by timonviola** [comment]
I can confirm it is working using the patch version. Thank for the help and the quick response!

**Comment by jwodder** [comment]
The patch has now been released in `versioningit` v3.1.2.
